name: haplotype-reconstruction3
channels:
  - stephenshank
  - davebx
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake
  - pysam
  - numpy
  - biopython
  - pandas
  - scikit-learn
  - matplotlib
  - convex-qsr
  - scipy
  - seaborn>=0.9
  - art
  - fastp
  - bowtie2
  - samtools
  - emboss
  - r-tidyverse
  - mafft
  - r-regresshaplo
  - r-seqinr
  - r-jsonlite
  - bioconductor-rsamtools
  - bioconductor-genomicalignments
