name: haplotype-reconstruction3
channels:
  - stephenshank
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake=5.10.0
  - pysam=0.15.4
  - numpy=1.18.1
  - biopython=1.74
  - pandas=0.25.3
  - scikit-learn=0.22.1
  - matplotlib=3.1.2
  - convex-qsr=0.2.0
  - scipy=1.4.1
